/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Restaurant;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void restaurant() {
                Restaurant restaurant = new Restaurant("Pizza Palace", 4, "$$$");
                assertEquals(restaurant.getName(),"Pizza Palace");
                assertEquals(restaurant.getStars(),4);
                assertEquals(restaurant.getPriceCategory(),"$$$");
            }
    @Test void review() {
        Review review = new Review("good", "ismail", 5);
        assertEquals(review.toString(),"body= good, author= ismail, rate= 5");
    }

        }

